name: Seat Monitor

on:
  schedule:
    # 每5分钟运行一次 (UTC时间)
    - cron: '*/5 * * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        
    - name: Install Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run seat monitor
      run: |
        echo "开始运行座位监控 - $(date)"
        python sq.py $(date +%Y-%m-%d)
        echo "监控完成 - $(date)"
        
    - name: Show log if exists
      run: |
        if [ -f "seat_monitor.log" ]; then
          echo "=== 最新日志 ==="
          tail -20 seat_monitor.log
        fi
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.csv *.log
        if git diff --staged --quiet; then
          echo "没有新的数据变更"
        else
          git commit -m "📊 座位数据更新 $(date '+%Y-%m-%d %H:%M UTC')"
          git push
          echo "数据已提交到仓库"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
